#!/usr/bin/env python3
"""Real Server + Core processes, using an AgentENV wire fixture or real Docker.

By default Responses is also a fixture. --live uses explicit APORTO_LIVE_*
environment variables; it never loads user configuration. No host shell tool is
executed. This is NOT a Firecracker/microVM acceptance test.
"""
import argparse
import email.parser
import email.policy
import json
import os
from pathlib import Path
import secrets
import signal
import shutil
import socket
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, urlsplit
from urllib.request import Request, build_opener, ProxyHandler

HTTP = build_opener(ProxyHandler({}))


def toml_value(value):
    """Encode the small typed configuration generated by this integration test."""
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, dict):
        return "{ " + ", ".join(toml_value(key) + " = " + toml_value(item) for key, item in value.items()) + " }"
    if isinstance(value, list):
        return "[" + ", ".join(map(toml_value, value)) + "]"
    if isinstance(value, int):
        return str(value)
    raise TypeError(type(value).__name__)


def frame(payload):
    return b"\0" + len(payload).to_bytes(4, "big") + payload


class Fixture(BaseHTTPRequestHandler):
    def log_message(self, *_):
        pass

    def reply(self, body=b"", status=200, content_type="application/json"):
        if not isinstance(body, bytes):
            body = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def responses_stream(self, output, number):
        """Hold the first response until public progress is read via real Core/HTTP."""
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.end_headers()

        def emit(kind, **payload):
            data = json.dumps({"type": kind, **payload}, ensure_ascii=False).encode()
            self.wfile.write(b"event: " + kind.encode() + b"\r\ndata: " + data + b"\r\n\r\n")
            self.wfile.flush()

        for index, item in enumerate(output):
            if item["type"] == "message":
                emit("response.output_item.added", output_index=index,
                     item={**item, "content": [], "status": "in_progress"})
                text = item["content"][0]["text"]
                for part in (text[:3], text[3:]):
                    emit("response.output_text.delta", output_index=index, content_index=0,
                         item_id=item["id"], delta=part)
                    if number == 1 and part == text[:3]:
                        assert self.server.progress_read.wait(15), "public streamed text was not observable before response completion"
            emit("response.output_item.done", output_index=index, item=item)
        emit("response.completed", response={"id": f"response-{number}", "status": "completed", "output": output})

    def do_GET(self):
        path = urlsplit(self.path)
        if path.path == "/files":
            assert self.headers["X-Access-Token"] == "fixture-envd"
            target = parse_qs(path.query)["path"][0]
            with self.server.lock:
                self.server.reads.append(target)
                value = self.server.files.get(target)
            self.reply(value or b"missing", 200 if value is not None else 404, "text/plain")
        else:
            self.reply(status=404)

    def do_DELETE(self):
        if urlsplit(self.path).path == "/sandboxes/stack-sandbox":
            assert self.headers["X-API-Key"] == "fixture-aenv-key"
            with self.server.lock:
                self.server.deletes += 1
                self.server.files.clear()
            self.reply(status=204)
        else:
            self.reply(status=404)

    def do_POST(self):
        data = self.rfile.read(int(self.headers.get("Content-Length", "0")))
        path = urlsplit(self.path)
        state = self.server
        if path.path in ("/v2/sandboxes", "/v2/sandboxes/stack-sandbox/connect"):
            assert self.headers["X-API-Key"] == "fixture-aenv-key"
            with state.lock:
                if path.path == "/v2/sandboxes":
                    state.creates += 1
                else:
                    state.connects += 1
            self.reply({"sandboxID": "stack-sandbox", "envdAccessToken": "fixture-envd"})
        elif path.path == "/sandboxes/stack-sandbox/pause":
            with state.lock:
                state.pauses += 1
            self.reply(status=204)
        elif path.path == "/sandboxes/stack-sandbox/refreshes":
            self.reply(status=204)
        elif path.path == "/process.Process/Start":
            # Independent protobuf encoding: PID 42, clean exit. Only broker's
            # directory setup is expected; this fixture does not model shell execution.
            self.reply(frame(bytes([10, 4, 10, 2, 8, 42])) + frame(bytes([10, 4, 26, 2, 8, 0])),
                       content_type="application/connect+proto")
        elif path.path == "/files":
            assert self.headers["X-Access-Token"] == "fixture-envd"
            target = parse_qs(path.query)["path"][0]
            message = email.parser.BytesParser(policy=email.policy.default).parsebytes(
                b"Content-Type: " + self.headers["Content-Type"].encode() + b"\r\n\r\n" + data)
            content = next(message.iter_parts()).get_payload(decode=True)
            with state.lock:
                state.files[target] = content
                state.writes.append(target)
            self.reply({})
        elif path.path == "/v1/responses":
            request = json.loads(data)
            assert len(request["tools"]) == 2
            assert {tool["name"] for tool in request["tools"]} == {"exec", "wait"}
            assert not request["parallel_tool_calls"]
            assert request["stream"] is True
            with state.lock:
                state.rounds += 1
                n = state.rounds
            if n == 1:
                source = "text(await tools.write_file({path:'persistent.txt',content:" + json.dumps(state.nonce) + "})); text(await tools.read_file({path:'persistent.txt'}));"
                if state.docker:
                    source = "text(await tools.read_skill({name:'code-review'})); text(await tools.mcp__policy__review_policy({})); text(await tools.exec_command({command:'printf docker-verified > command.txt'})); " + source
            elif n == 3:
                assert any(v.get("type") == "custom_tool_call_output" for v in request["input"])
                assert any(v.get("role") == "assistant" for v in request["input"])
                source = "text(await tools.read_file({path:'persistent.txt'}));"
            else:
                source = None
            message = {"id": f"message-{n}", "type": "message", "role": "assistant", "status": "completed",
                       "phase": "commentary" if source else "final_answer",
                       "content": [{"type": "output_text", "text": "开始检查文件。" if source else state.nonce}]}
            output = [message]
            if source:
                output.append({"type": "custom_tool_call", "name": "exec", "call_id": f"stack-{n}", "input": source})
            self.responses_stream(output, n)
        else:
            self.reply(status=404)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin-dir", type=Path, default=Path("target/debug"))
    parser.add_argument("--live", action="store_true")
    parser.add_argument("--mode", choices=["local", "remote"], default="local")
    parser.add_argument("--runtime", choices=["agentenv", "docker"], default="agentenv")
    parser.add_argument("--docker-image", default="python:3.12-slim")
    parser.add_argument("--docker-host", default="unix:///var/run/docker.sock")
    args = parser.parse_args()
    if args.runtime == "docker" and args.mode != "local":
        parser.error("Docker supports local mode only")
    binary = args.bin_dir.resolve()
    token = secrets.token_hex(32)
    fixture = ThreadingHTTPServer(("127.0.0.1", 0), Fixture)
    fixture.lock = threading.Lock()
    fixture.progress_read = threading.Event()
    fixture.files, fixture.reads, fixture.writes = {}, [], []
    fixture.creates = fixture.connects = fixture.pauses = fixture.deletes = fixture.rounds = 0
    fixture.nonce = "stack-receipt-" + secrets.token_hex(12)
    fixture.docker = args.runtime == "docker"
    threading.Thread(target=fixture.serve_forever, daemon=True).start()
    endpoint = f"http://127.0.0.1:{fixture.server_port}"
    started = time.monotonic()
    process = None
    container_id = None
    report = None
    with tempfile.TemporaryDirectory(prefix="aporto-stack-") as temp:
        directory = Path(temp)
        env = dict(os.environ, STACK_SERVER_TOKEN=token, STACK_RUNTIME_KEY="fixture-aenv-key",
                   STACK_MODEL_KEY=os.environ.get("APORTO_LIVE_KEY", "fixture-model-key") if args.live else "fixture-model-key")
        model = os.environ["APORTO_LIVE_MODEL"] if args.live else "stack-fixture"
        model_endpoint = os.environ["APORTO_LIVE_ENDPOINT"] if args.live else endpoint + "/v1/responses"
        provider_headers = json.loads(os.environ.get("APORTO_LIVE_HEADERS", "{}")) if args.live else {}
        # Keep all provider header values in process env, never in the config file.
        header_env = {}
        for index, (key, value) in enumerate(provider_headers.items()):
            name = f"STACK_HEADER_{index}"
            header_env[key], env[name] = name, value
        runtime_spec = ({"provider": "docker", "image": args.docker_image} if fixture.docker else
                        {"provider": "agentenv", "template": "fixture"})
        declarations = ""
        if fixture.docker:
            example = Path(__file__).resolve().parent.parent / "examples/reviewer"
            shutil.copytree(example / "mcp", directory / "mcp")
            shutil.copytree(example / "skills", directory / "skills")
            declarations = '\n[[skills]]\nsource = "skills/code-review"\n[[mcp]]\nname = "policy"\nsource = "mcp/policy"\ncommand = ["python3", "server.py"]\n'
        agentfile = '[agent]\nname = "stack"\n\n[model]\nname = ' + toml_value(model) + '\nconnection = "primary"\n\n[runtime]\n'
        agentfile += "".join(key + " = " + toml_value(value) + "\n" for key, value in runtime_spec.items())
        (directory / "Agentfile").write_text(agentfile + declarations)
        bundle = directory / "stack.agent.json"
        subprocess.run([str(binary / "aporto"), "build", str(directory), "-o", str(bundle)],
                       check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        runtime_config = ({"host": args.docker_host} if fixture.docker else
                          {"mode": args.mode, "api_url": endpoint, "api_key": {"env": "STACK_RUNTIME_KEY"}, "lease_ms": 30000})
        config = '[connections.primary]\nendpoint = ' + toml_value(model_endpoint) + '\napi_key = { env = "STACK_MODEL_KEY" }\n'
        if header_env:
            config += "\n[connections.primary.headers]\n"
            config += "".join(toml_value(key) + " = " + toml_value({"env": value}) + "\n" for key, value in header_env.items())
        config += '\n[[agents]]\nid = "stack"\nbundle = ' + toml_value(str(bundle)) + '\n\n[agents.runtime]\n'
        config += "".join(key + " = " + toml_value(value) + "\n" for key, value in runtime_config.items())
        deployment = directory / "deployment.toml"
        deployment.write_text(config)
        subprocess.run([str(binary / "aporto"), "activate", "--config", str(deployment), "--agent", "stack"],
                       check=True, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        log = (directory / "server.log").open("w+")
        with socket.socket() as probe:
            probe.bind(("127.0.0.1", 0))
            port = probe.getsockname()[1]
        base = f"http://127.0.0.1:{port}"

        def docker(*arguments):
            return subprocess.check_output(["docker", "--host", args.docker_host, *arguments], stderr=subprocess.PIPE, timeout=20)

        def inspect_container(identifier):
            info = json.loads(docker("inspect", identifier))[0]
            assert info["Config"]["Labels"]["io.aporto.managed"] == "true"
            return info

        def verify_stopped_container(identifier):
            info = inspect_container(identifier)
            assert info["State"]["Status"] == "exited", "idle Docker workspace must be stopped"
            assert not info["HostConfig"]["Privileged"] and not info["Mounts"]
            assert info["HostConfig"]["NetworkMode"] == "none"
            assert "ALL" in info["HostConfig"]["CapDrop"]
            assert info["HostConfig"]["Memory"] == 512 * 1024 * 1024
            docker("cp", identifier + ":/workspace/persistent.txt", str(directory / "download.txt"))
            assert (directory / "download.txt").read_text() == fixture.nonce

        def api(path, data=None, auth=True, expected=200):
            headers = {"Authorization": "Bearer " + token} if auth else {}
            if data is not None:
                headers["Content-Type"] = "application/json"
            req = Request(base + path, json.dumps(data).encode() if data is not None else None, headers)
            try:
                response = HTTP.open(req, timeout=10)
            except HTTPError as error:
                response = error
            assert response.status == expected, f"{path}: HTTP {response.status}, expected {expected}"
            return json.load(response)

        def launch():
            child = subprocess.Popen([str(binary / "aporto-server"), "--core-bin", str(binary / "aporto-core"),
                "--core-config", str(deployment), "--state-dir", str(directory / "state"),
                "--listen", f"127.0.0.1:{port}", "--token-env", "STACK_SERVER_TOKEN"], env=env,
                stdout=log, stderr=log)
            for _ in range(100):
                if child.poll() is not None:
                    raise RuntimeError("server exited at startup; no credentials logged")
                try:
                    api("/v1/agents")
                    return child
                except (URLError, ConnectionError):
                    time.sleep(0.05)
            child.kill()
            child.wait()
            raise RuntimeError("server startup deadline exceeded")

        def wait_turn(thread_id, turn_id):
            for _ in range(1200):
                result = api("/v1/threads/" + thread_id)
                turn = next(t for t in result["turns"] if t["id"] == turn_id)
                if not args.live and not fixture.progress_read.is_set():
                    page = api(f"/v1/threads/{thread_id}/turns/{turn_id}/items")
                    if any(item["kind"] == "assistant_message" and item["status"] == "in_progress" and item["text"] for item in page["items"]):
                        assert turn["status"] == "running"
                        fixture.progress_read.set()
                if turn["status"] in ("completed", "failed", "interrupted"):
                    assert turn["status"] == "completed", f"turn {turn['status']}: {turn.get('error')}"
                    assert fixture.nonce in turn["output"], "model did not return verified receipt"
                    return result
                time.sleep(0.1)
            raise RuntimeError("turn completion deadline exceeded")

        def all_pages(path, field, after=0):
            values = []
            while True:
                page = api(path + f"?after={after}")
                values.extend(page[field])
                assert page["next_cursor"] >= after
                if not page["has_more"]:
                    return values, page["next_cursor"]
                assert page["next_cursor"] > after
                after = page["next_cursor"]

        def transcript(thread_id, turn_id):
            items, _ = all_pages(f"/v1/threads/{thread_id}/turns/{turn_id}/items", "items")
            assert len({item["id"] for item in items}) == len(items)
            assert all(item["turn_id"] == turn_id and item["status"] != "in_progress" for item in items)
            assert any(item["kind"] == "assistant_message" and fixture.nonce in (item.get("text") or "") for item in items)
            assert any(item["kind"] == "ptc_call" and item.get("input") for item in items)
            assert any(item["kind"] == "tool_call" and item.get("name") == "read_file" and fixture.nonce in (item.get("output") or "") for item in items)
            if not args.live:
                assert any(item["phase"] == "commentary" and item["text"] == "开始检查文件。" for item in items)
            return items

        try:
            process = launch()
            api("/v1/agents", auth=False, expected=401)
            thread = api("/v1/threads", {"agent_id":"stack", "title":"process integration"}, expected=201)
            thread_id = thread["id"]
            prompt = f"Use tools.write_file to write exactly {fixture.nonce} to persistent.txt, then use tools.read_file to verify the file. Return its exact content. The file operations are mandatory."
            if fixture.docker:
                prompt += " Also read the packaged code-review skill using read_skill, call mcp__policy__review_policy, and use exec_command to execute `printf docker-verified > command.txt`. All three tool calls are mandatory."
            path = f"/v1/threads/{thread_id}/turns"
            first = api(path, {"input":prompt,"idempotency_key":"one"}, expected=202)
            result = wait_turn(thread_id, first["id"])
            first_items = transcript(thread_id, first["id"])
            container_id = result["thread"]["sandbox_id"]
            if fixture.docker:
                verify_stopped_container(container_id)
                docker("cp", container_id + ":/workspace/command.txt", str(directory / "command.txt"))
                assert (directory / "command.txt").read_text() == "docker-verified"
            else:
                assert container_id == "stack-sandbox"
            assert api(path, {"input":prompt,"idempotency_key":"one"}, expected=202)["id"] == first["id"]
            api(path, {"input":"different","idempotency_key":"one"}, expected=409)
            initial_events, cursor = all_pages(f"/v1/threads/{thread_id}/events/page", "events")
            if fixture.docker:
                calls = {e["data"].get("name") for e in initial_events if e["kind"] == "tool.completed" and e["data"].get("success")}
                assert {"read_file","write_file","read_skill","mcp__policy__review_policy","exec_command"}.issubset(calls)
            replayed_items = {}
            for event in initial_events:
                if event["kind"].startswith("item."):
                    item = event["data"]["item"]
                    assert item["sequence"] == event["sequence"]
                    replayed_items[item["id"]] = item
            assert sorted(replayed_items.values(), key=lambda item: item["ordinal"]) == first_items
            # Test SIGTERM drain and a fresh Core process opening the existing DB.
            process.send_signal(signal.SIGTERM)
            assert process.wait(timeout=45) == 0, "server failed graceful SIGTERM"
            process = launch()
            assert transcript(thread_id, first["id"]) == first_items
            read_prompt = "Use tools.read_file to read persistent.txt from the existing workspace and return its exact contents. Actually read it again; do not write it or answer from memory."
            second = api(path, {"input":read_prompt,"idempotency_key":"two"}, expected=202)
            result = wait_turn(thread_id, second["id"])
            transcript(thread_id, second["id"])
            assert result["thread"]["sandbox_id"] == container_id
            if fixture.docker:
                verify_stopped_container(container_id)
            replay, _ = all_pages(f"/v1/threads/{thread_id}/events/page", "events", cursor)
            assert replay and all(e["sequence"] > cursor for e in replay)
            assert any(e["kind"] == "turn.completed" for e in replay)
            if fixture.docker:
                second_calls = [e["data"] for e in replay if e["turn_id"] == second["id"] and e["kind"] == "tool.completed"]
                assert any(call.get("name") == "read_file" and call.get("success") for call in second_calls), "resumed turn must actually read the file"
                assert not any(call.get("name") == "write_file" for call in second_calls), "resumed turn must not rewrite the file"
                with sqlite3.connect(directory / "state/state.sqlite") as db:
                    history = json.loads(db.execute("SELECT history_json FROM threads WHERE id=?", (thread_id,)).fetchone()[0])
                last_user = max(i for i, item in enumerate(history) if item.get("role") == "user")
                returned = [item for item in history[last_user+1:] if item.get("type") == "custom_tool_call_output"]
                assert any(fixture.nonce in item.get("output", "") for item in returned), "model must receive the re-read content"
            request = Request(base + f"/v1/threads/{thread_id}/events?after={cursor}", headers={"Authorization":"Bearer " + token})
            with HTTP.open(request, timeout=10) as stream:
                event_lines = [stream.readline().decode() for _ in range(3)]
                assert any("agent_event" in line for line in event_lines)
            if fixture.docker:
                assert fixture.creates == fixture.connects == fixture.pauses == fixture.deletes == 0
            else:
                assert fixture.creates == 2 and fixture.deletes == 1 and fixture.connects == 1 and fixture.pauses == 2
                assert fixture.files["/workspace/persistent.txt"].decode() == fixture.nonce
                assert fixture.reads.count("/workspace/persistent.txt") >= 2
                assert fixture.writes.count("/workspace/persistent.txt") == 1
            # Credentials do not enter the persisted DB or public event payloads.
            persisted = b"".join(p.read_bytes() for p in (directory / "state").glob("state.sqlite*"))
            for value in (token, "fixture-aenv-key", env["STACK_MODEL_KEY"]):
                assert value.encode() not in persisted
            evidence = ({"containers":1,"container_reconnects":1,"stopped_between_turns":True,"stdio_mcp":True,"packaged_skill":True}
                        if fixture.docker else {"sandbox_creates":fixture.creates,"activation_cleanup":fixture.deletes,"sandbox_reconnects":fixture.connects,
                        "pauses":fixture.pauses,"reads":len(fixture.reads),"writes":len(fixture.writes)})
            report = {"result":"passed","model":"live" if args.live else "fixture", "runtime":"real Docker" if fixture.docker else "HTTP wire fixture",
                "runtime_mode":args.mode,"turns":2,**evidence,
                "activation":True,"restart":True,"sse_replay":True,"transcript_restore":True,"transcript_replay_matches_snapshot":True,
                "streamed_before_response_completed":fixture.progress_read.is_set() if not args.live else None,
                "elapsed_seconds":round(time.monotonic()-started,3)}
        finally:
            primary_error = sys.exc_info()[1]
            cleanup_errors = []
            try:
                if process and process.poll() is None:
                    process.send_signal(signal.SIGTERM)
                    try:
                        process.wait(timeout=45)
                    except subprocess.TimeoutExpired:
                        process.kill()
                        process.wait(timeout=5)
            except Exception as error:
                cleanup_errors.append(type(error).__name__)
            if fixture.docker:
                # Only IDs persisted by this private test DB may be removed.
                database = directory / "state/state.sqlite"
                if database.exists():
                    identifiers = []
                    try:
                        with sqlite3.connect(database) as db:
                            identifiers = [row[0] for row in db.execute("SELECT sandbox_id FROM threads WHERE sandbox_id IS NOT NULL")]
                    except Exception as error:
                        cleanup_errors.append(type(error).__name__)
                    for identifier in identifiers:
                        try:
                            inspect_container(identifier)
                            docker("rm", "--force", identifier)
                        except Exception as error:
                            cleanup_errors.append(type(error).__name__)
            fixture.shutdown()
            fixture.server_close()
            log.close()
            if cleanup_errors:
                error = RuntimeError("test resource cleanup failed: " + ", ".join(cleanup_errors))
                if primary_error is None:
                    raise error
                if hasattr(primary_error, "add_note"):
                    primary_error.add_note(str(error))
    print(json.dumps(report))


if __name__ == "__main__":
    main()
